# Generated by Django 5.0 on 2023-12-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
